name: "Laravel Test App"
git: true
env:
  APP_NAME: "Test App"
php-packages:
  - wyattcast44/laravelschema
php-packages-dev:
  - brianium/paratest
npm-packages:
 - "autoprefixer@latest"
mkdir:
  - "resources/svg"
touch:
  - "app/Support/helpers.php"
artisan:
  - "storage:link"
console:
  - "code ."